namespace Everdue.Server.Application.Abstractions;

/// <summary>
/// Where attachment bytes live. One implementation today (the data directory); an S3-compatible
/// backend for the hosted version becomes a registration change rather than a refactor, which is the
/// entire reason the interface exists this early.
///
/// Keys are opaque and generated by the caller — never a user-supplied filename.
/// </summary>
public interface IFileStore
{
    Task SaveAsync(string key, Stream content, CancellationToken cancellationToken = default);

    /// <summary>Null when the record exists but the bytes do not — a restored database over an empty disk.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    Task DeleteAsync(string key, CancellationToken cancellationToken = default);
}
